"use client";
import Link from "next/link";
import { ClientOnly } from "@/components/ClientOnly";
import { useOabData } from "@/hooks/useOabData";
import { sampleQuestions } from "@/lib/sampleData";
import { clearAllData, saveQuestions } from "@/lib/storage";
function HomeContent(){const{stats,questions,refresh}=useOabData(); const loadSamples=()=>{saveQuestions(sampleQuestions);refresh()}; const clear=()=>{if(confirm("Tem certeza que deseja apagar questões e simulados deste navegador?")){clearAllData();refresh()}}; return <div className="grid" style={{gap:22}}><section className="hero"><div className="card"><h1>Estude para a OAB com simulados inteligentes.</h1><p className="lead">Importe questões em JSON, aplique o gabarito oficial, valide o conteúdo e faça simulados usando apenas questões revisadas.</p><div className="actions"><Link className="btn" href="/importar">Importar JSON</Link><Link className="btn secondary" href="/estudo">Área de estudo</Link>
            <Link className="btn secondary" href="/simulado">Iniciar simulado</Link><Link className="btn secondary" href="/banco">Banco de questões</Link></div></div><div className="card"><h2>Fluxo seguro</h2><p className="muted">Esta versão não lê PDF automaticamente. Ela usa JSON revisado, evitando palavras quebradas, acentos corrompidos e questões misturadas.</p><div className="notice">Somente questões com status <strong>validado</strong> entram no simulado.</div></div></section><section className="grid grid-3"><div className="stat"><strong>{stats.totalQuestions}</strong><span>questões no banco</span></div><div className="stat"><strong>{stats.validatedQuestions}</strong><span>questões validadas</span></div><div className="stat"><strong>{stats.simulations}</strong><span>simulados feitos</span></div></section><section className="grid grid-2"><div className="card"><h2>Disciplinas</h2>{stats.subjects.length===0?<p className="muted">Nenhuma questão importada ainda.</p>:<div className="grid">{stats.subjects.slice(0,8).map(item=><div className="stat" key={item.subject}><strong style={{fontSize:"1.2rem"}}>{item.subject}</strong><span>{item.count} questões</span></div>)}</div>}</div><div className="card"><h2>Primeiro uso</h2><p className="muted">Você pode carregar 3 questões fictícias para testar o sistema, ou importar diretamente o JSON da prova da OAB.</p><div className="actions"><button className="btn" onClick={loadSamples}>Carregar exemplos</button><button className="btn danger" onClick={clear} disabled={!questions.length&&!stats.simulations}>Limpar dados</button></div></div></section></div>}
export default function Home(){return <ClientOnly><HomeContent/></ClientOnly>}
